// Bengali names for the address dropdowns, plus the older romanisations people
// still type. Search-only data: the value written to an order stays the English
// name in bd-geo.ts / bd-thanas.ts, so nothing downstream (couriers, shipping
// zones, reports) has to learn a second spelling of the same place.
//
// Districts are complete. Thanas cover only the two districts bd-thanas.ts has
// area lists for at all — everything else is free text there anyway.

/** English district name → Bengali. Keys match BD_DISTRICTS_BY_DIVISION exactly. */
export const BD_DISTRICT_BN: Record<string, string> = {
  Bagerhat: 'বাগেরহাট',
  Bandarban: 'বান্দরবান',
  Barguna: 'বরগুনা',
  Barishal: 'বরিশাল',
  Bhola: 'ভোলা',
  Bogura: 'বগুড়া',
  Brahmanbaria: 'ব্রাহ্মণবাড়িয়া',
  Chandpur: 'চাঁদপুর',
  Chapainawabganj: 'চাঁপাইনবাবগঞ্জ',
  Chattogram: 'চট্টগ্রাম',
  Chuadanga: 'চুয়াডাঙ্গা',
  "Cox's Bazar": 'কক্সবাজার',
  Cumilla: 'কুমিল্লা',
  Dhaka: 'ঢাকা',
  'Dhaka Sub-Urban': 'ঢাকা শহরতলি',
  Dinajpur: 'দিনাজপুর',
  Faridpur: 'ফরিদপুর',
  Feni: 'ফেনী',
  Gaibandha: 'গাইবান্ধা',
  Gazipur: 'গাজীপুর',
  Gopalganj: 'গোপালগঞ্জ',
  Habiganj: 'হবিগঞ্জ',
  Jamalpur: 'জামালপুর',
  Jashore: 'যশোর',
  Jhalokati: 'ঝালকাঠি',
  Jhenaidah: 'ঝিনাইদহ',
  Joypurhat: 'জয়পুরহাট',
  Khagrachari: 'খাগড়াছড়ি',
  Khulna: 'খুলনা',
  Kishoreganj: 'কিশোরগঞ্জ',
  Kurigram: 'কুড়িগ্রাম',
  Kushtia: 'কুষ্টিয়া',
  Lakshmipur: 'লক্ষ্মীপুর',
  Lalmonirhat: 'লালমনিরহাট',
  Madaripur: 'মাদারীপুর',
  Magura: 'মাগুরা',
  Manikganj: 'মানিকগঞ্জ',
  Meherpur: 'মেহেরপুর',
  Moulvibazar: 'মৌলভীবাজার',
  Munshiganj: 'মুন্সিগঞ্জ',
  Mymensingh: 'ময়মনসিংহ',
  Naogaon: 'নওগাঁ',
  Narail: 'নড়াইল',
  Narayanganj: 'নারায়ণগঞ্জ',
  Narsingdi: 'নরসিংদী',
  Natore: 'নাটোর',
  Netrokona: 'নেত্রকোণা',
  Nilphamari: 'নীলফামারী',
  Noakhali: 'নোয়াখালী',
  Pabna: 'পাবনা',
  Panchagarh: 'পঞ্চগড়',
  Patuakhali: 'পটুয়াখালী',
  Pirojpur: 'পিরোজপুর',
  Rajbari: 'রাজবাড়ী',
  Rajshahi: 'রাজশাহী',
  Rangamati: 'রাঙ্গামাটি',
  Rangpur: 'রংপুর',
  Satkhira: 'সাতক্ষীরা',
  Shariatpur: 'শরীয়তপুর',
  Sherpur: 'শেরপুর',
  Sirajganj: 'সিরাজগঞ্জ',
  Sunamganj: 'সুনামগঞ্জ',
  Sylhet: 'সিলেট',
  Tangail: 'টাঙ্গাইল',
  Thakurgaon: 'ঠাকুরগাঁও',
};

/**
 * Older romanisations and courier shorthand, for the districts that were
 * renamed or are habitually abbreviated. Someone who has typed "Comilla" for
 * twenty years should not have to learn that the form calls it Cumilla.
 */
export const BD_DISTRICT_ALT_SPELLINGS: Record<string, string[]> = {
  Barishal: ['Barisal', 'BAR'],
  Bogura: ['Bogra'],
  Brahmanbaria: ['B Baria', 'Bbaria'],
  Chapainawabganj: ['Chapai', 'Nawabganj'],
  Chattogram: ['Chittagong', 'Ctg', 'CTG'],
  "Cox's Bazar": ['Coxs Bazar', 'Cox Bazar', 'Coxsbazar'],
  Cumilla: ['Comilla'],
  Dhaka: ['DHK'],
  'Dhaka Sub-Urban': ['Dhaka Suburban', 'Savar', 'Keraniganj', 'Ashulia'],
  Jashore: ['Jessore'],
  Jhalokati: ['Jhalakathi'],
  Khulna: ['KHL'],
  Munshiganj: ['Bikrampur'],
  Mymensingh: ['MYM'],
  Netrokona: ['Netrakona'],
  Rajshahi: ['RAJ'],
  Rangpur: ['RNG'],
  Sylhet: ['SYL'],
};

/** English thana/area name → Bengali, for the districts that have area lists. */
export const BD_THANA_BN: Record<string, string> = {
  // Dhaka Sub-Urban
  Ashulia: 'আশুলিয়া',
  Dhamrai: 'ধামরাই',
  Dohar: 'দোহার',
  Hemayetpur: 'হেমায়েতপুর',
  'Keraniganj Model': 'কেরানীগঞ্জ মডেল',
  Nawabganj: 'নবাবগঞ্জ',
  Savar: 'সাভার',
  'South Keraniganj': 'দক্ষিণ কেরানীগঞ্জ',
  // Dhaka
  Adabor: 'আদাবর',
  Airport: 'বিমানবন্দর',
  'Ati Bazar (Keraniganj)': 'আটি বাজার (কেরানীগঞ্জ)',
  Azompur: 'আজমপুর',
  Badda: 'বাড্ডা',
  Banani: 'বনানী',
  Bangshal: 'বংশাল',
  'Bashundhara R/A': 'বসুন্ধরা আবাসিক',
  'Battery Section': 'ব্যাটারি সেকশন',
  Bhashantek: 'ভাষানটেক',
  Cantonment: 'ক্যান্টনমেন্ট',
  Chalkbazar: 'চকবাজার',
  'Dakshin khan': 'দক্ষিণখান',
  'Darus Salam': 'দারুস সালাম',
  Demra: 'ডেমরা',
  Dhanmondi: 'ধানমন্ডি',
  Gandaria: 'গেন্ডারিয়া',
  Gulistan: 'গুলিস্তান',
  Gulshan: 'গুলশান',
  Hatirjheel: 'হাতিরঝিল',
  Hazaribag: 'হাজারীবাগ',
  Jatrabari: 'যাত্রাবাড়ী',
  Kadamtali: 'কদমতলী',
  Kafrul: 'কাফরুল',
  Kalabagan: 'কলাবাগান',
  Kamrangirchar: 'কামরাঙ্গীরচর',
  Khilgaon: 'খিলগাঁও',
  Khilkhet: 'খিলক্ষেত',
  Kotwali: 'কোতোয়ালী',
  Lalbagh: 'লালবাগ',
  Mirpur: 'মিরপুর',
  Mohammadpur: 'মোহাম্মদপুর',
  Motijheel: 'মতিঝিল',
  Mugda: 'মুগদা',
  'New Market': 'নিউ মার্কেট',
  Pallabi: 'পল্লবী',
  Paltan: 'পল্টন',
  Panthapath: 'পান্থপথ',
  Purbachal: 'পূর্বাচল',
  Ramna: 'রমনা',
  Rampura: 'রামপুরা',
  Rupnagar: 'রূপনগর',
  Sabujbag: 'সবুজবাগ',
  'Shah Ali': 'শাহ আলী',
  'Shah Ali Market': 'শাহ আলী মার্কেট',
  Shahbag: 'শাহবাগ',
  Shahjahanpur: 'শাহজাহানপুর',
  'Sher-e-Bangla Nagar': 'শেরেবাংলা নগর',
  Shyampur: 'শ্যামপুর',
  Sutrapur: 'সূত্রাপুর',
  Tejgaon: 'তেজগাঁও',
  'Tejgaon Industrial Area': 'তেজগাঁও শিল্প এলাকা',
  Turag: 'তুরাগ',
  Uttara: 'উত্তরা',
  Uttarkhan: 'উত্তরখান',
  Vasantek: 'ভাসানটেক',
  Vatara: 'ভাটারা',
  Wari: 'ওয়ারী',
  'Zone Not Clear': 'এলাকা অনিশ্চিত',
  // Upazilas for the other 63 districts, added alongside their English
  // lists in bd-thanas.ts. Shown as the `hint` under each option and
  // registered as a search alias, so staff can type either script.
  Abhaynagar: 'অভয়নগর',
  Adamdighi: 'আদমদীঘি',
  Aditmari: 'আদিতমারী',
  Agailjhara: 'আগৈলঝাড়া',
  Ajmiriganj: 'আজমিরীগঞ্জ',
  Akhaura: 'আখাউড়া',
  Akkelpur: 'আক্কেলপুর',
  Alamdanga: 'আলমডাঙ্গা',
  Alfadanga: 'আলফাডাঙ্গা',
  Alikadam: 'আলীকদম',
  Amtali: 'আমতলী',
  Anowara: 'আনোয়ারা',
  Araihazar: 'আড়াইহাজার',
  Ashuganj: 'আশুগঞ্জ',
  Assasuni: 'আশাশুনি',
  Atgharia: 'আটঘরিয়া',
  Atpara: 'আটপাড়া',
  Atrai: 'আত্রাই',
  Atwari: 'আটোয়ারী',
  Austagram: 'অষ্টগ্রাম',
  Babuganj: 'বাবুগঞ্জ',
  Badalgachhi: 'বদলগাছী',
  Badarganj: 'বদরগঞ্জ',
  Bagatipara: 'বাগাতিপাড়া',
  'Bagerhat Sadar': 'বাগেরহাট সদর',
  Bagha: 'বাঘা',
  Baghaichhari: 'বাঘাইছড়ি',
  Bagherpara: 'বাঘারপাড়া',
  Bagmara: 'বাগমারা',
  Bahubal: 'বাহুবল',
  Bajitpur: 'বাজিতপুর',
  Bakerganj: 'বাকেরগঞ্জ',
  Baksiganj: 'বকশীগঞ্জ',
  Balaganj: 'বালাগঞ্জ',
  Baliadangi: 'বালিয়াডাঙ্গী',
  Baliakandi: 'বালিয়াকান্দি',
  Bamna: 'বামনা',
  Banaripara: 'বানারীপাড়া',
  Bancharampur: 'বাঞ্ছারামপুর',
  Bandar: 'বন্দর',
  'Bandarban Sadar': 'বান্দরবান সদর',
  Baniyachong: 'বানিয়াচং',
  Banshkhali: 'বাঁশখালী',
  Baraigram: 'বড়াইগ্রাম',
  'Barguna Sadar': 'বরগুনা সদর',
  Barhatta: 'বারহাট্টা',
  'Barishal Sadar': 'বরিশাল সদর',
  Barkal: 'বরকল',
  Barlekha: 'বড়লেখা',
  Barura: 'বরুড়া',
  Basail: 'বাসাইল',
  Batiaghata: 'বটিয়াঘাটা',
  Bauphal: 'বাউফল',
  Beanibazar: 'বিয়ানীবাজার',
  Begumganj: 'বেগমগঞ্জ',
  Belabo: 'বেলাবো',
  Belaichhari: 'বিলাইছড়ি',
  Belkuchi: 'বেলকুচি',
  Bera: 'বেড়া',
  Betagi: 'বেতাগী',
  Bhairab: 'ভৈরব',
  Bhaluka: 'ভালুকা',
  Bhandaria: 'ভাণ্ডারিয়া',
  Bhanga: 'ভাঙ্গা',
  Bhangura: 'ভাঙ্গুড়া',
  Bhedarganj: 'ভেদরগঞ্জ',
  Bheramara: 'ভেড়ামারা',
  'Bhola Sadar': 'ভোলা সদর',
  Bholahat: 'ভোলাহাট',
  Bhuapur: 'ভূঞাপুর',
  Bhurungamari: 'ভুরুঙ্গামারী',
  Bijoynagar: 'বিজয়নগর',
  Biral: 'বিরল',
  Birampur: 'বিরামপুর',
  Birganj: 'বীরগঞ্জ',
  Bishwamvarpur: 'বিশ্বম্ভরপুর',
  Bishwanath: 'বিশ্বনাথ',
  Boalkhali: 'বোয়ালখালী',
  Boalmari: 'বোয়ালমারী',
  Bochaganj: 'বোচাগঞ্জ',
  Boda: 'বোদা',
  'Bogura Sadar': 'বগুড়া সদর',
  'Brahmanbaria Sadar': 'ব্রাহ্মণবাড়িয়া সদর',
  Brahmanpara: 'ব্রাহ্মণপাড়া',
  Burhanuddin: 'বোরহানউদ্দিন',
  Burichang: 'বুড়িচং',
  Chakaria: 'চকরিয়া',
  Chandanaish: 'চন্দনাইশ',
  Chandina: 'চান্দিনা',
  'Chandpur Sadar': 'চাঁদপুর সদর',
  'Chapainawabganj Sadar': 'চাঁপাইনবাবগঞ্জ সদর',
  'Char Fasson': 'চরফ্যাশন',
  'Char Rajibpur': 'চর রাজিবপুর',
  Charbhadrasan: 'চরভদ্রাসন',
  Charghat: 'চারঘাট',
  Chatkhil: 'চাটখিল',
  Chatmohar: 'চাটমোহর',
  Chauddagram: 'চৌদ্দগ্রাম',
  Chaugachha: 'চৌগাছা',
  Chauhali: 'চৌহালী',
  Chhagalnaiya: 'ছাগলনাইয়া',
  Chhatak: 'ছাতক',
  Chilmari: 'চিলমারী',
  Chirirbandar: 'চিরিরবন্দর',
  Chitalmari: 'চিতলমারী',
  'Chuadanga Sadar': 'চুয়াডাঙ্গা সদর',
  Chunarughat: 'চুনারুঘাট',
  Companiganj: 'কোম্পানীগঞ্জ',
  "Cox's Bazar Sadar": 'কক্সবাজার সদর',
  'Cumilla Adarsha Sadar': 'কুমিল্লা আদর্শ সদর',
  'Cumilla Sadar Dakshin': 'কুমিল্লা সদর দক্ষিণ',
  Dacope: 'দাকোপ',
  Daganbhuiyan: 'দাগনভূঞা',
  'Dakshin Surma': 'দক্ষিণ সুরমা',
  Damudya: 'ডামুড্যা',
  Damurhuda: 'দামুড়হুদা',
  Dasar: 'ডাসার',
  Dashmina: 'দশমিনা',
  Daudkandi: 'দাউদকান্দি',
  Daulatkhan: 'দৌলতখান',
  Daulatpur: 'দৌলতপুর',
  Debhata: 'দেবহাটা',
  Debidwar: 'দেবিদ্বার',
  Debiganj: 'দেবীগঞ্জ',
  Delduar: 'দেলদুয়ার',
  Derai: 'দিরাই',
  Dewanganj: 'দেওয়ানগঞ্জ',
  Dhamoirhat: 'ধামইরহাট',
  Dhanbari: 'ধনবাড়ী',
  Dharampasha: 'ধর্মপাশা',
  Dhobaura: 'ধোবাউড়া',
  Dhunat: 'ধুনট',
  Dhupchanchia: 'ধুপচাঁচিয়া',
  Dighalia: 'দিঘলিয়া',
  Dighinala: 'দীঘিনালা',
  Dimla: 'ডিমলা',
  'Dinajpur Sadar': 'দিনাজপুর সদর',
  Domar: 'ডোমার',
  Dowarabazar: 'দোয়ারাবাজার',
  Dumki: 'দুমকী',
  Dumuria: 'ডুমুরিয়া',
  Durgapur: 'দুর্গাপুর',
  Eidgaon: 'ঈদগাঁও',
  Fakirhat: 'ফকিরহাট',
  Faridganj: 'ফরিদগঞ্জ',
  'Faridpur Sadar': 'ফরিদপুর সদর',
  Fatikchhari: 'ফটিকছড়ি',
  Fenchuganj: 'ফেঞ্চুগঞ্জ',
  'Feni Sadar': 'ফেনী সদর',
  Fulbaria: 'ফুলবাড়িয়া',
  Fulgazi: 'ফুলগাজী',
  Gabtali: 'গাবতলী',
  Gaffargaon: 'গফরগাঁও',
  'Gaibandha Sadar': 'গাইবান্ধা সদর',
  Galachipa: 'গলাচিপা',
  Gangachhara: 'গংগাচড়া',
  Gangni: 'গাংনী',
  Gauripur: 'গৌরীপুর',
  Gaurnadi: 'গৌরনদী',
  Gazaria: 'গজারিয়া',
  'Gazipur Sadar': 'গাজীপুর সদর',
  Ghatail: 'ঘাটাইল',
  Ghior: 'ঘিওর',
  Ghoraghat: 'ঘোড়াঘাট',
  Goalandaghat: 'গোয়ালন্দ ঘাট',
  Gobindaganj: 'গোবিন্দগঞ্জ',
  Godagari: 'গোদাগাড়ী',
  Golapganj: 'গোলাপগঞ্জ',
  Gomastapur: 'গোমস্তাপুর',
  'Gopalganj Sadar': 'গোপালগঞ্জ সদর',
  Gopalpur: 'গোপালপুর',
  Gosairhat: 'গোসাইরহাট',
  Gowainghat: 'গোয়াইনঘাট',
  Guimara: 'গুইমারা',
  Gurudaspur: 'গুরুদাসপুর',
  'Habiganj Sadar': 'হবিগঞ্জ সদর',
  Haimchar: 'হাইমচর',
  Hakimpur: 'হাকিমপুর',
  Haluaghat: 'হালুয়াঘাট',
  Harinakunda: 'হরিণাকুণ্ডু',
  Haripur: 'হরিপুর',
  Harirampur: 'হরিরামপুর',
  Hathazari: 'হাটহাজারী',
  Hatibandha: 'হাতীবান্ধা',
  Hatiya: 'হাতিয়া',
  Haziganj: 'হাজীগঞ্জ',
  Hizla: 'হিজলা',
  Homna: 'হোমনা',
  Hossainpur: 'হোসেনপুর',
  Ishwardi: 'ঈশ্বরদী',
  Ishwarganj: 'ঈশ্বরগঞ্জ',
  Islampur: 'ইসলামপুর',
  Itna: 'ইটনা',
  Jagannathpur: 'জগন্নাথপুর',
  Jaintiapur: 'জৈন্তাপুর',
  Jaldhaka: 'জলঢাকা',
  Jamalganj: 'জামালগঞ্জ',
  'Jamalpur Sadar': 'জামালপুর সদর',
  'Jashore Sadar': 'যশোর সদর',
  'Jhalokati Sadar': 'ঝালকাঠি সদর',
  'Jhenaidah Sadar': 'ঝিনাইদহ সদর',
  Jhenaigati: 'ঝিনাইগাতী',
  Jhikargachha: 'ঝিকরগাছা',
  Jibannagar: 'জীবননগর',
  'Joypurhat Sadar': 'জয়পুরহাট সদর',
  Juraichhari: 'জুরাছড়ি',
  Juri: 'জুড়ী',
  Kabirhat: 'কবিরহাট',
  Kachua: 'কচুয়া',
  Kahaloo: 'কাহালু',
  Kaharole: 'কাহারোল',
  Kalai: 'কালাই',
  Kalapara: 'কলাপাড়া',
  Kalaroa: 'কলারোয়া',
  Kalia: 'কালিয়া',
  Kaliakair: 'কালিয়াকৈর',
  Kaliganj: 'কালীগঞ্জ',
  Kalihati: 'কালিহাতী',
  Kalkini: 'কালকিনি',
  Kalmakanda: 'কলমাকান্দা',
  Kalukhali: 'কালুখালী',
  Kamalganj: 'কমলগঞ্জ',
  Kamalnagar: 'কমলনগর',
  Kamarkhanda: 'কামারখন্দ',
  Kanaighat: 'কানাইঘাট',
  Kapasia: 'কাপাসিয়া',
  Kaptai: 'কাপ্তাই',
  Karimganj: 'করিমগঞ্জ',
  Karnaphuli: 'কর্ণফুলী',
  Kasba: 'কসবা',
  Kashiani: 'কাশিয়ানী',
  Kathalia: 'কাঠালিয়া',
  Katiadi: 'কটিয়াদী',
  Kaukhali: 'কাউখালী',
  Kaunia: 'কাউনিয়া',
  Kazipur: 'কাজীপুর',
  Kendua: 'কেন্দুয়া',
  Keshabpur: 'কেশবপুর',
  'Khagrachhari Sadar': 'খাগড়াছড়ি সদর',
  Khaliajuri: 'খালিয়াজুরী',
  Khansama: 'খানসামা',
  Khetlal: 'ক্ষেতলাল',
  Khoksa: 'খোকসা',
  'Kishoreganj Sadar': 'কিশোরগঞ্জ সদর',
  Kotalipara: 'কোটালীপাড়া',
  Kotchandpur: 'কোটচাঁদপুর',
  Koyra: 'কয়রা',
  Kulaura: 'কুলাউড়া',
  Kuliarchar: 'কুলিয়ারচর',
  Kumarkhali: 'কুমারখালী',
  'Kurigram Sadar': 'কুড়িগ্রাম সদর',
  'Kushtia Sadar': 'কুষ্টিয়া সদর',
  Kutubdia: 'কুতুবদিয়া',
  Lakhai: 'লাখাই',
  Laksam: 'লাকসাম',
  Lakshmichhari: 'লক্ষ্মীছড়ি',
  'Lakshmipur Sadar': 'লক্ষ্মীপুর সদর',
  Lalmohan: 'লালমোহন',
  'Lalmonirhat Sadar': 'লালমনিরহাট সদর',
  Lalpur: 'লালপুর',
  Lama: 'লামা',
  Langadu: 'লংগদু',
  Lohagara: 'লোহাগাড়া',
  Lohajang: 'লৌহজং',
  Madan: 'মদন',
  Madarganj: 'মাদারগঞ্জ',
  'Madaripur Sadar': 'মাদারীপুর সদর',
  Madhabpur: 'মাধবপুর',
  Madhukhali: 'মধুখালী',
  Madhupur: 'মধুপুর',
  Madhyanagar: 'মধ্যনগর',
  'Magura Sadar': 'মাগুরা সদর',
  Mahadebpur: 'মহাদেবপুর',
  Mahalchhari: 'মহালছড়ি',
  Maheshkhali: 'মহেশখালী',
  Maheshpur: 'মহেশপুর',
  Manda: 'মান্দা',
  Manikchhari: 'মানিকছড়ি',
  'Manikganj Sadar': 'মানিকগঞ্জ সদর',
  Manirampur: 'মণিরামপুর',
  Manoharganj: 'মনোহরগঞ্জ',
  Manpura: 'মনপুরা',
  Mathbaria: 'মঠবাড়িয়া',
  Matiranga: 'মাটিরাঙ্গা',
  'Matlab Dakshin': 'মতলব দক্ষিণ',
  'Matlab Uttar': 'মতলব উত্তর',
  Meghna: 'মেঘনা',
  Mehendiganj: 'মেহেন্দিগঞ্জ',
  'Meherpur Sadar': 'মেহেরপুর সদর',
  Melandaha: 'মেলান্দহ',
  Mirsharai: 'মীরসরাই',
  Mirzaganj: 'মির্জাগঞ্জ',
  Mirzapur: 'মির্জাপুর',
  Mithamain: 'মিঠামইন',
  Mithapukur: 'মিঠাপুকুর',
  Mohanganj: 'মোহনগঞ্জ',
  Mohanpur: 'মোহনপুর',
  Mollahat: 'মোল্লাহাট',
  Mongla: 'মোংলা',
  Monohardi: 'মনোহরদী',
  Morrelganj: 'মোড়েলগঞ্জ',
  'Moulvibazar Sadar': 'মৌলভীবাজার সদর',
  Mujibnagar: 'মুজিবনগর',
  Muksudpur: 'মুকসুদপুর',
  Muktagachha: 'মুক্তাগাছা',
  Muladi: 'মুলাদী',
  'Munshiganj Sadar': 'মুন্সিগঞ্জ সদর',
  Muradnagar: 'মুরাদনগর',
  'Mymensingh Sadar': 'ময়মনসিংহ সদর',
  Nabiganj: 'নবীগঞ্জ',
  Nabinagar: 'নবীনগর',
  Nachole: 'নাচোল',
  Nagarkanda: 'নগরকান্দা',
  Nagarpur: 'নাগরপুর',
  Nageshwari: 'নাগেশ্বরী',
  Naikhongchhari: 'নাইক্ষ্যংছড়ি',
  Nakla: 'নকলা',
  Nalchity: 'নলছিটি',
  Naldanga: 'নলডাঙ্গা',
  Nalitabari: 'নালিতাবাড়ী',
  Nandail: 'নান্দাইল',
  Nandigram: 'নন্দীগ্রাম',
  Nangalkot: 'নাঙ্গলকোট',
  Naniarchar: 'নানিয়ারচর',
  'Naogaon Sadar': 'নওগাঁ সদর',
  'Narail Sadar': 'নড়াইল সদর',
  'Narayanganj Sadar': 'নারায়ণগঞ্জ সদর',
  Naria: 'নড়িয়া',
  'Narsingdi Sadar': 'নরসিংদী সদর',
  Nasirnagar: 'নাসিরনগর',
  'Natore Sadar': 'নাটোর সদর',
  Nazirpur: 'নাজিরপুর',
  'Nesarabad (Swarupkathi)': 'নেছারাবাদ (স্বরূপকাঠি)',
  'Netrokona Sadar': 'নেত্রকোণা সদর',
  Niamatpur: 'নিয়ামতপুর',
  Nikli: 'নিকলী',
  'Nilphamari Sadar': 'নীলফামারী সদর',
  'Noakhali Sadar': 'নোয়াখালী সদর',
  'Osmani Nagar': 'ওসমানীনগর',
  Paba: 'পবা',
  'Pabna Sadar': 'পাবনা সদর',
  Paikgachha: 'পাইকগাছা',
  Pakundia: 'পাকুন্দিয়া',
  Palash: 'পলাশ',
  Palashbari: 'পলাশবাড়ী',
  'Panchagarh Sadar': 'পঞ্চগড় সদর',
  Panchbibi: 'পাঁচবিবি',
  Panchhari: 'পানছড়ি',
  Pangsha: 'পাংশা',
  Parbatipur: 'পার্বতীপুর',
  Parshuram: 'পরশুরাম',
  Patgram: 'পাটগ্রাম',
  Patharghata: 'পাথরঘাটা',
  Patiya: 'পটিয়া',
  Patnitala: 'পত্নীতলা',
  'Patuakhali Sadar': 'পটুয়াখালী সদর',
  Pekua: 'পেকুয়া',
  Phulbari: 'ফুলবাড়ী',
  Phulchhari: 'ফুলছড়ি',
  Phulpur: 'ফুলপুর',
  Phultala: 'ফুলতলা',
  Pirgachha: 'পীরগাছা',
  Pirganj: 'পীরগঞ্জ',
  'Pirojpur Sadar': 'পিরোজপুর সদর',
  Porsha: 'পোরশা',
  Purbadhala: 'পূর্বধলা',
  Puthia: 'পুঠিয়া',
  Raiganj: 'রায়গঞ্জ',
  Raipur: 'রায়পুর',
  Raipura: 'রায়পুরা',
  Rajapur: 'রাজাপুর',
  Rajarhat: 'রাজারহাট',
  Rajasthali: 'রাজস্থলী',
  'Rajbari Sadar': 'রাজবাড়ী সদর',
  Rajnagar: 'রাজনগর',
  Rajoir: 'রাজৈর',
  Ramganj: 'রামগঞ্জ',
  Ramgarh: 'রামগড়',
  Ramgati: 'রামগতি',
  Rampal: 'রামপাল',
  Ramu: 'রামু',
  Rangabali: 'রাঙ্গাবালী',
  'Rangamati Sadar': 'রাঙ্গামাটি সদর',
  'Rangpur Sadar': 'রংপুর সদর',
  Rangunia: 'রাঙ্গুনিয়া',
  Raninagar: 'রাণীনগর',
  Ranisankail: 'রাণীশংকৈল',
  Raomari: 'রৌমারী',
  Raozan: 'রাউজান',
  Rowangchhari: 'রোয়াংছড়ি',
  Ruma: 'রুমা',
  Rupganj: 'রূপগঞ্জ',
  Rupsha: 'রূপসা',
  Sadarpur: 'সদরপুর',
  Sadullapur: 'সাদুল্লাপুর',
  Saghata: 'সাঘাটা',
  Saidpur: 'সৈয়দপুর',
  Sakhipur: 'সখীপুর',
  Saltha: 'সালথা',
  Sandwip: 'সন্দ্বীপ',
  Santhia: 'সাঁথিয়া',
  Sapahar: 'সাপাহার',
  Sarail: 'সরাইল',
  Sarankhola: 'শরণখোলা',
  Sariakandi: 'সারিয়াকান্দি',
  Sarishabari: 'সরিষাবাড়ী',
  Satkania: 'সাতকানিয়া',
  'Satkhira Sadar': 'সাতক্ষীরা সদর',
  Saturia: 'সাটুরিয়া',
  Senbagh: 'সেনবাগ',
  Shahjadpur: 'শাহজাদপুর',
  Shahrasti: 'শাহরাস্তি',
  Shailkupa: 'শৈলকুপা',
  Shajahanpur: 'শাজাহানপুর',
  Shalikha: 'শালিখা',
  Shantiganj: 'শান্তিগঞ্জ',
  'Shariatpur Sadar': 'শরীয়তপুর সদর',
  Sharsha: 'শার্শা',
  Shayestaganj: 'শায়েস্তাগঞ্জ',
  'Sherpur Sadar': 'শেরপুর সদর',
  Shibchar: 'শিবচর',
  Shibganj: 'শিবগঞ্জ',
  Shibpur: 'শিবপুর',
  Shivalaya: 'শিবালয়',
  Shyamnagar: 'শ্যামনগর',
  Singair: 'সিংগাইর',
  Singra: 'সিংড়া',
  Sirajdikhan: 'সিরাজদিখান',
  'Sirajganj Sadar': 'সিরাজগঞ্জ সদর',
  Sitakunda: 'সীতাকুণ্ড',
  Sonagazi: 'সোনাগাজী',
  Sonaimuri: 'সোনাইমুড়ী',
  Sonargaon: 'সোনারগাঁও',
  Sonatala: 'সোনাতলা',
  Sreebardi: 'শ্রীবরদী',
  Sreemangal: 'শ্রীমঙ্গল',
  Sreenagar: 'শ্রীনগর',
  Sreepur: 'শ্রীপুর',
  Subarnachar: 'সুবর্ণচর',
  Sujanagar: 'সুজানগর',
  Sullah: 'শাল্লা',
  'Sunamganj Sadar': 'সুনামগঞ্জ সদর',
  Sundarganj: 'সুন্দরগঞ্জ',
  'Sylhet Sadar': 'সিলেট সদর',
  Tahirpur: 'তাহিরপুর',
  Tala: 'তালা',
  Taltali: 'তালতলী',
  'Tangail Sadar': 'টাঙ্গাইল সদর',
  Tanore: 'তানোর',
  Taraganj: 'তারাগঞ্জ',
  Tarail: 'তাড়াইল',
  Tarakanda: 'তারাকান্দা',
  Tarash: 'তাড়াশ',
  Tazumuddin: 'তজুমদ্দিন',
  Teknaf: 'টেকনাফ',
  Terokhada: 'তেরখাদা',
  Tetulia: 'তেঁতুলিয়া',
  'Thakurgaon Sadar': 'ঠাকুরগাঁও সদর',
  Thanchi: 'থানচি',
  Titas: 'তিতাস',
  Tongibari: 'টঙ্গিবাড়ী',
  Trishal: 'ত্রিশাল',
  Tungipara: 'টুঙ্গিপাড়া',
  Ukhia: 'উখিয়া',
  Ulipur: 'উলিপুর',
  Ullapara: 'উল্লাপাড়া',
  Wazirpur: 'উজিরপুর',
  Zajira: 'জাজিরা',
  Zakiganj: 'জকিগঞ্জ',
  'Zianagar (Indurkani)': 'জিয়ানগর (ইন্দুরকানি)',
  // These four are missing above only because the same word is also a
  // DISTRICT name (Sherpur, Kishoreganj, Faridpur) or a near-duplicate of
  // another district's spelling (Pirojpur's Kawkhali vs Rangamati's
  // Kaukhali). BD_THANA_BN is looked up by thana name, so each needs its own
  // entry regardless of what BD_DISTRICT_BN holds.
  Sherpur: 'শেরপুর',
  Kishoreganj: 'কিশোরগঞ্জ',
  Faridpur: 'ফরিদপুর',
  Kawkhali: 'কাউখালী',
};
