// Bengali names for the address dropdowns, plus the older romanisations people
// still type. Search-only data: the value written to an order stays the English
// name in bd-geo.ts / bd-thanas.ts, so nothing downstream (couriers, shipping
// zones, reports) has to learn a second spelling of the same place.
//
// Districts are complete. Thanas cover only the two districts bd-thanas.ts has
// area lists for at all — everything else is free text there anyway.

/** English district name → Bengali. Keys match BD_DISTRICTS_BY_DIVISION exactly. */
export const BD_DISTRICT_BN: Record<string, string> = {
  Bagerhat: 'বাগেরহাট',
  Bandarban: 'বান্দরবান',
  Barguna: 'বরগুনা',
  Barishal: 'বরিশাল',
  Bhola: 'ভোলা',
  Bogura: 'বগুড়া',
  Brahmanbaria: 'ব্রাহ্মণবাড়িয়া',
  Chandpur: 'চাঁদপুর',
  Chapainawabganj: 'চাঁপাইনবাবগঞ্জ',
  Chattogram: 'চট্টগ্রাম',
  Chuadanga: 'চুয়াডাঙ্গা',
  "Cox's Bazar": 'কক্সবাজার',
  Cumilla: 'কুমিল্লা',
  Dhaka: 'ঢাকা',
  'Dhaka Sub-Urban': 'ঢাকা শহরতলি',
  Dinajpur: 'দিনাজপুর',
  Faridpur: 'ফরিদপুর',
  Feni: 'ফেনী',
  Gaibandha: 'গাইবান্ধা',
  Gazipur: 'গাজীপুর',
  Gopalganj: 'গোপালগঞ্জ',
  Habiganj: 'হবিগঞ্জ',
  Jamalpur: 'জামালপুর',
  Jashore: 'যশোর',
  Jhalokati: 'ঝালকাঠি',
  Jhenaidah: 'ঝিনাইদহ',
  Joypurhat: 'জয়পুরহাট',
  Khagrachari: 'খাগড়াছড়ি',
  Khulna: 'খুলনা',
  Kishoreganj: 'কিশোরগঞ্জ',
  Kurigram: 'কুড়িগ্রাম',
  Kushtia: 'কুষ্টিয়া',
  Lakshmipur: 'লক্ষ্মীপুর',
  Lalmonirhat: 'লালমনিরহাট',
  Madaripur: 'মাদারীপুর',
  Magura: 'মাগুরা',
  Manikganj: 'মানিকগঞ্জ',
  Meherpur: 'মেহেরপুর',
  Moulvibazar: 'মৌলভীবাজার',
  Munshiganj: 'মুন্সিগঞ্জ',
  Mymensingh: 'ময়মনসিংহ',
  Naogaon: 'নওগাঁ',
  Narail: 'নড়াইল',
  Narayanganj: 'নারায়ণগঞ্জ',
  Narsingdi: 'নরসিংদী',
  Natore: 'নাটোর',
  Netrokona: 'নেত্রকোণা',
  Nilphamari: 'নীলফামারী',
  Noakhali: 'নোয়াখালী',
  Pabna: 'পাবনা',
  Panchagarh: 'পঞ্চগড়',
  Patuakhali: 'পটুয়াখালী',
  Pirojpur: 'পিরোজপুর',
  Rajbari: 'রাজবাড়ী',
  Rajshahi: 'রাজশাহী',
  Rangamati: 'রাঙ্গামাটি',
  Rangpur: 'রংপুর',
  Satkhira: 'সাতক্ষীরা',
  Shariatpur: 'শরীয়তপুর',
  Sherpur: 'শেরপুর',
  Sirajganj: 'সিরাজগঞ্জ',
  Sunamganj: 'সুনামগঞ্জ',
  Sylhet: 'সিলেট',
  Tangail: 'টাঙ্গাইল',
  Thakurgaon: 'ঠাকুরগাঁও',
};

/**
 * Older romanisations and courier shorthand, for the districts that were
 * renamed or are habitually abbreviated. Someone who has typed "Comilla" for
 * twenty years should not have to learn that the form calls it Cumilla.
 */
export const BD_DISTRICT_ALT_SPELLINGS: Record<string, string[]> = {
  Barishal: ['Barisal', 'BAR'],
  Bogura: ['Bogra'],
  Brahmanbaria: ['B Baria', 'Bbaria'],
  Chapainawabganj: ['Chapai', 'Nawabganj'],
  Chattogram: ['Chittagong', 'Ctg', 'CTG'],
  "Cox's Bazar": ['Coxs Bazar', 'Cox Bazar', 'Coxsbazar'],
  Cumilla: ['Comilla'],
  Dhaka: ['DHK'],
  'Dhaka Sub-Urban': ['Dhaka Suburban', 'Savar', 'Keraniganj', 'Ashulia'],
  Jashore: ['Jessore'],
  Jhalokati: ['Jhalakathi'],
  Khulna: ['KHL'],
  Munshiganj: ['Bikrampur'],
  Mymensingh: ['MYM'],
  Netrokona: ['Netrakona'],
  Rajshahi: ['RAJ'],
  Rangpur: ['RNG'],
  Sylhet: ['SYL'],
};

/** English thana/area name → Bengali, for the districts that have area lists. */
export const BD_THANA_BN: Record<string, string> = {
  // Dhaka Sub-Urban
  Ashulia: 'আশুলিয়া',
  Dhamrai: 'ধামরাই',
  Dohar: 'দোহার',
  Hemayetpur: 'হেমায়েতপুর',
  'Keraniganj Model': 'কেরানীগঞ্জ মডেল',
  Nawabganj: 'নবাবগঞ্জ',
  Savar: 'সাভার',
  'South Keraniganj': 'দক্ষিণ কেরানীগঞ্জ',
  // Dhaka
  Adabor: 'আদাবর',
  Airport: 'বিমানবন্দর',
  'Ati Bazar (Keraniganj)': 'আটি বাজার (কেরানীগঞ্জ)',
  Azompur: 'আজমপুর',
  Badda: 'বাড্ডা',
  Banani: 'বনানী',
  Bangshal: 'বংশাল',
  'Bashundhara R/A': 'বসুন্ধরা আবাসিক',
  'Battery Section': 'ব্যাটারি সেকশন',
  Bhashantek: 'ভাষানটেক',
  Cantonment: 'ক্যান্টনমেন্ট',
  Chalkbazar: 'চকবাজার',
  'Dakshin khan': 'দক্ষিণখান',
  'Darus Salam': 'দারুস সালাম',
  Demra: 'ডেমরা',
  Dhanmondi: 'ধানমন্ডি',
  Gandaria: 'গেন্ডারিয়া',
  Gulistan: 'গুলিস্তান',
  Gulshan: 'গুলশান',
  Hatirjheel: 'হাতিরঝিল',
  Hazaribag: 'হাজারীবাগ',
  Jatrabari: 'যাত্রাবাড়ী',
  Kadamtali: 'কদমতলী',
  Kafrul: 'কাফরুল',
  Kalabagan: 'কলাবাগান',
  Kamrangirchar: 'কামরাঙ্গীরচর',
  Khilgaon: 'খিলগাঁও',
  Khilkhet: 'খিলক্ষেত',
  Kotwali: 'কোতোয়ালী',
  Lalbagh: 'লালবাগ',
  Mirpur: 'মিরপুর',
  Mohammadpur: 'মোহাম্মদপুর',
  Motijheel: 'মতিঝিল',
  Mugda: 'মুগদা',
  'New Market': 'নিউ মার্কেট',
  Pallabi: 'পল্লবী',
  Paltan: 'পল্টন',
  Panthapath: 'পান্থপথ',
  Purbachal: 'পূর্বাচল',
  Ramna: 'রমনা',
  Rampura: 'রামপুরা',
  Rupnagar: 'রূপনগর',
  Sabujbag: 'সবুজবাগ',
  'Shah Ali': 'শাহ আলী',
  'Shah Ali Market': 'শাহ আলী মার্কেট',
  Shahbag: 'শাহবাগ',
  Shahjahanpur: 'শাহজাহানপুর',
  'Sher-e-Bangla Nagar': 'শেরেবাংলা নগর',
  Shyampur: 'শ্যামপুর',
  Sutrapur: 'সূত্রাপুর',
  Tejgaon: 'তেজগাঁও',
  'Tejgaon Industrial Area': 'তেজগাঁও শিল্প এলাকা',
  Turag: 'তুরাগ',
  Uttara: 'উত্তরা',
  Uttarkhan: 'উত্তরখান',
  Vasantek: 'ভাসানটেক',
  Vatara: 'ভাটারা',
  Wari: 'ওয়ারী',
  'Zone Not Clear': 'এলাকা অনিশ্চিত',
};
