// Thana/delivery-area lists per district, keyed to match BD_DISTRICTS_BY_
// DIVISION's district names exactly. Sourced directly from Steadfast's own
// merchant-panel area picker (not the official government upazila list) —
// per explicit request, so the checkout dropdown only ever offers values
// Steadfast itself already recognizes as real delivery zones, deduplicated
// (the source list had literal duplicate entries, e.g. two "Kadamtali").
//
// Dhaka and Dhaka Sub-Urban keep those Steadfast-sourced METROPOLITAN lists.
// Every other district below is the official upazila list instead, because
// Steadfast's picker only ever covered those two: measured, 2 of 65 districts
// had any entry at all, so the other 63 offered an empty dropdown and the
// thana could not be filled in at all.
//
// Safe to widen. `area` reaches Steadfast only inside the free-text
// `recipient_address` string that ShipmentsService assembles (addressLine,
// area, landmark, district, postCode) — it is never sent as a zone id they
// validate, so an official upazila name they spell differently costs nothing.
// Both pickers accept free text anyway (ThanaAutocomplete), so a name missing
// here can still be typed.
export const BD_THANAS_BY_DISTRICT: Record<string, string[]> = {
  // Key must match BD_DISTRICTS_BY_DIVISION exactly, or AddressFields falls
  // back to free text and the dropdown silently never appears.
  'Dhaka Sub-Urban': [
    'Ashulia',
    'Dhamrai',
    'Dohar',
    'Hemayetpur',
    'Keraniganj Model',
    'Nawabganj',
    'Savar',
    'South Keraniganj',
  ],
  Dhaka: [
    'Adabor',
    'Airport',
    'Ati Bazar (Keraniganj)',
    'Azompur',
    'Badda',
    'Banani',
    'Bangshal',
    'Bashundhara R/A',
    'Battery Section',
    'Bhashantek',
    'Cantonment',
    'Chalkbazar',
    'Dakshin khan',
    'Darus Salam',
    'Demra',
    'Dhanmondi',
    'Gandaria',
    'Gulistan',
    'Gulshan',
    'Hatirjheel',
    'Hazaribag',
    'Jatrabari',
    'Kadamtali',
    'Kafrul',
    'Kalabagan',
    'Kamrangirchar',
    'Khilgaon',
    'Khilkhet',
    'Kotwali',
    'Lalbagh',
    'Mirpur',
    'Mohammadpur',
    'Motijheel',
    'Mugda',
    'New Market',
    'Pallabi',
    'Paltan',
    'Panthapath',
    'Purbachal',
    'Ramna',
    'Rampura',
    'Rupnagar',
    'Sabujbag',
    'Shah Ali',
    'Shah Ali Market',
    'Shahbag',
    'Shahjahanpur',
    'Sher-e-Bangla Nagar',
    'Shyampur',
    'Sutrapur',
    'Tejgaon',
    'Tejgaon Industrial Area',
    'Turag',
    'Uttara',
    'Uttarkhan',
    'Vasantek',
    'Vatara',
    'Wari',
    'Zone Not Clear',
  ],
  Bagerhat: [
    'Bagerhat Sadar',
    'Chitalmari',
    'Fakirhat',
    'Kachua',
    'Mollahat',
    'Mongla',
    'Morrelganj',
    'Rampal',
    'Sarankhola',
  ],
  Bandarban: [
    'Alikadam',
    'Bandarban Sadar',
    'Lama',
    'Naikhongchhari',
    'Rowangchhari',
    'Ruma',
    'Thanchi',
  ],
  Barguna: [
    'Amtali',
    'Bamna',
    'Barguna Sadar',
    'Betagi',
    'Patharghata',
    'Taltali',
  ],
  Barishal: [
    'Agailjhara',
    'Babuganj',
    'Bakerganj',
    'Banaripara',
    'Barishal Sadar',
    'Gaurnadi',
    'Hizla',
    'Mehendiganj',
    'Muladi',
    'Wazirpur',
  ],
  Bhola: [
    'Bhola Sadar',
    'Burhanuddin',
    'Char Fasson',
    'Daulatkhan',
    'Lalmohan',
    'Manpura',
    'Tazumuddin',
  ],
  Bogura: [
    'Adamdighi',
    'Bogura Sadar',
    'Dhunat',
    'Dhupchanchia',
    'Gabtali',
    'Kahaloo',
    'Nandigram',
    'Sariakandi',
    'Shajahanpur',
    'Sherpur',
    'Shibganj',
    'Sonatala',
  ],
  Brahmanbaria: [
    'Akhaura',
    'Ashuganj',
    'Bancharampur',
    'Bijoynagar',
    'Brahmanbaria Sadar',
    'Kasba',
    'Nabinagar',
    'Nasirnagar',
    'Sarail',
  ],
  Chandpur: [
    'Chandpur Sadar',
    'Faridganj',
    'Haimchar',
    'Haziganj',
    'Kachua',
    'Matlab Dakshin',
    'Matlab Uttar',
    'Shahrasti',
  ],
  Chapainawabganj: [
    'Bholahat',
    'Chapainawabganj Sadar',
    'Gomastapur',
    'Nachole',
    'Shibganj',
  ],
  Chattogram: [
    'Anowara',
    'Banshkhali',
    'Boalkhali',
    'Chandanaish',
    'Fatikchhari',
    'Hathazari',
    'Karnaphuli',
    'Lohagara',
    'Mirsharai',
    'Patiya',
    'Rangunia',
    'Raozan',
    'Sandwip',
    'Satkania',
    'Sitakunda',
  ],
  Chuadanga: [
    'Alamdanga',
    'Chuadanga Sadar',
    'Damurhuda',
    'Jibannagar',
  ],
  "Cox's Bazar": [
    'Chakaria',
    'Cox\'s Bazar Sadar',
    'Eidgaon',
    'Kutubdia',
    'Maheshkhali',
    'Pekua',
    'Ramu',
    'Teknaf',
    'Ukhia',
  ],
  Cumilla: [
    'Barura',
    'Brahmanpara',
    'Burichang',
    'Chandina',
    'Chauddagram',
    'Cumilla Adarsha Sadar',
    'Cumilla Sadar Dakshin',
    'Daudkandi',
    'Debidwar',
    'Homna',
    'Laksam',
    'Manoharganj',
    'Meghna',
    'Muradnagar',
    'Nangalkot',
    'Titas',
  ],
  Dinajpur: [
    'Biral',
    'Birampur',
    'Birganj',
    'Bochaganj',
    'Chirirbandar',
    'Dinajpur Sadar',
    'Ghoraghat',
    'Hakimpur',
    'Kaharole',
    'Khansama',
    'Nawabganj',
    'Parbatipur',
    'Phulbari',
  ],
  Faridpur: [
    'Alfadanga',
    'Bhanga',
    'Boalmari',
    'Charbhadrasan',
    'Faridpur Sadar',
    'Madhukhali',
    'Nagarkanda',
    'Sadarpur',
    'Saltha',
  ],
  Feni: [
    'Chhagalnaiya',
    'Daganbhuiyan',
    'Feni Sadar',
    'Fulgazi',
    'Parshuram',
    'Sonagazi',
  ],
  Gaibandha: [
    'Gaibandha Sadar',
    'Gobindaganj',
    'Palashbari',
    'Phulchhari',
    'Sadullapur',
    'Saghata',
    'Sundarganj',
  ],
  Gazipur: [
    'Gazipur Sadar',
    'Kaliakair',
    'Kaliganj',
    'Kapasia',
    'Sreepur',
  ],
  Gopalganj: [
    'Gopalganj Sadar',
    'Kashiani',
    'Kotalipara',
    'Muksudpur',
    'Tungipara',
  ],
  Habiganj: [
    'Ajmiriganj',
    'Bahubal',
    'Baniyachong',
    'Chunarughat',
    'Habiganj Sadar',
    'Lakhai',
    'Madhabpur',
    'Nabiganj',
    'Shayestaganj',
  ],
  Jamalpur: [
    'Baksiganj',
    'Dewanganj',
    'Islampur',
    'Jamalpur Sadar',
    'Madarganj',
    'Melandaha',
    'Sarishabari',
  ],
  Jashore: [
    'Abhaynagar',
    'Bagherpara',
    'Chaugachha',
    'Jashore Sadar',
    'Jhikargachha',
    'Keshabpur',
    'Manirampur',
    'Sharsha',
  ],
  Jhalokati: [
    'Jhalokati Sadar',
    'Kathalia',
    'Nalchity',
    'Rajapur',
  ],
  Jhenaidah: [
    'Harinakunda',
    'Jhenaidah Sadar',
    'Kaliganj',
    'Kotchandpur',
    'Maheshpur',
    'Shailkupa',
  ],
  Joypurhat: [
    'Akkelpur',
    'Joypurhat Sadar',
    'Kalai',
    'Khetlal',
    'Panchbibi',
  ],
  Khagrachari: [
    'Dighinala',
    'Guimara',
    'Khagrachhari Sadar',
    'Lakshmichhari',
    'Mahalchhari',
    'Manikchhari',
    'Matiranga',
    'Panchhari',
    'Ramgarh',
  ],
  Khulna: [
    'Batiaghata',
    'Dacope',
    'Dighalia',
    'Dumuria',
    'Koyra',
    'Paikgachha',
    'Phultala',
    'Rupsha',
    'Terokhada',
  ],
  Kishoreganj: [
    'Austagram',
    'Bajitpur',
    'Bhairab',
    'Hossainpur',
    'Itna',
    'Karimganj',
    'Katiadi',
    'Kishoreganj Sadar',
    'Kuliarchar',
    'Mithamain',
    'Nikli',
    'Pakundia',
    'Tarail',
  ],
  Kurigram: [
    'Bhurungamari',
    'Char Rajibpur',
    'Chilmari',
    'Kurigram Sadar',
    'Nageshwari',
    'Phulbari',
    'Rajarhat',
    'Raomari',
    'Ulipur',
  ],
  Kushtia: [
    'Bheramara',
    'Daulatpur',
    'Khoksa',
    'Kumarkhali',
    'Kushtia Sadar',
    'Mirpur',
  ],
  Lakshmipur: [
    'Kamalnagar',
    'Lakshmipur Sadar',
    'Raipur',
    'Ramganj',
    'Ramgati',
  ],
  Lalmonirhat: [
    'Aditmari',
    'Hatibandha',
    'Kaliganj',
    'Lalmonirhat Sadar',
    'Patgram',
  ],
  Madaripur: [
    'Dasar',
    'Kalkini',
    'Madaripur Sadar',
    'Rajoir',
    'Shibchar',
  ],
  Magura: [
    'Magura Sadar',
    'Mohammadpur',
    'Shalikha',
    'Sreepur',
  ],
  Manikganj: [
    'Daulatpur',
    'Ghior',
    'Harirampur',
    'Manikganj Sadar',
    'Saturia',
    'Shivalaya',
    'Singair',
  ],
  Meherpur: [
    'Gangni',
    'Meherpur Sadar',
    'Mujibnagar',
  ],
  Moulvibazar: [
    'Barlekha',
    'Juri',
    'Kamalganj',
    'Kulaura',
    'Moulvibazar Sadar',
    'Rajnagar',
    'Sreemangal',
  ],
  Munshiganj: [
    'Gazaria',
    'Lohajang',
    'Munshiganj Sadar',
    'Sirajdikhan',
    'Sreenagar',
    'Tongibari',
  ],
  Mymensingh: [
    'Bhaluka',
    'Dhobaura',
    'Fulbaria',
    'Gaffargaon',
    'Gauripur',
    'Haluaghat',
    'Ishwarganj',
    'Muktagachha',
    'Mymensingh Sadar',
    'Nandail',
    'Phulpur',
    'Tarakanda',
    'Trishal',
  ],
  Naogaon: [
    'Atrai',
    'Badalgachhi',
    'Dhamoirhat',
    'Mahadebpur',
    'Manda',
    'Naogaon Sadar',
    'Niamatpur',
    'Patnitala',
    'Porsha',
    'Raninagar',
    'Sapahar',
  ],
  Narail: [
    'Kalia',
    'Lohagara',
    'Narail Sadar',
  ],
  Narayanganj: [
    'Araihazar',
    'Bandar',
    'Narayanganj Sadar',
    'Rupganj',
    'Sonargaon',
  ],
  Narsingdi: [
    'Belabo',
    'Monohardi',
    'Narsingdi Sadar',
    'Palash',
    'Raipura',
    'Shibpur',
  ],
  Natore: [
    'Bagatipara',
    'Baraigram',
    'Gurudaspur',
    'Lalpur',
    'Naldanga',
    'Natore Sadar',
    'Singra',
  ],
  Netrokona: [
    'Atpara',
    'Barhatta',
    'Durgapur',
    'Kalmakanda',
    'Kendua',
    'Khaliajuri',
    'Madan',
    'Mohanganj',
    'Netrokona Sadar',
    'Purbadhala',
  ],
  Nilphamari: [
    'Dimla',
    'Domar',
    'Jaldhaka',
    'Kishoreganj',
    'Nilphamari Sadar',
    'Saidpur',
  ],
  Noakhali: [
    'Begumganj',
    'Chatkhil',
    'Companiganj',
    'Hatiya',
    'Kabirhat',
    'Noakhali Sadar',
    'Senbagh',
    'Sonaimuri',
    'Subarnachar',
  ],
  Pabna: [
    'Atgharia',
    'Bera',
    'Bhangura',
    'Chatmohar',
    'Faridpur',
    'Ishwardi',
    'Pabna Sadar',
    'Santhia',
    'Sujanagar',
  ],
  Panchagarh: [
    'Atwari',
    'Boda',
    'Debiganj',
    'Panchagarh Sadar',
    'Tetulia',
  ],
  Patuakhali: [
    'Bauphal',
    'Dashmina',
    'Dumki',
    'Galachipa',
    'Kalapara',
    'Mirzaganj',
    'Patuakhali Sadar',
    'Rangabali',
  ],
  Pirojpur: [
    'Bhandaria',
    'Kawkhali',
    'Mathbaria',
    'Nazirpur',
    'Nesarabad (Swarupkathi)',
    'Pirojpur Sadar',
    'Zianagar (Indurkani)',
  ],
  Rajbari: [
    'Baliakandi',
    'Goalandaghat',
    'Kalukhali',
    'Pangsha',
    'Rajbari Sadar',
  ],
  Rajshahi: [
    'Bagha',
    'Bagmara',
    'Charghat',
    'Durgapur',
    'Godagari',
    'Mohanpur',
    'Paba',
    'Puthia',
    'Tanore',
  ],
  Rangamati: [
    'Baghaichhari',
    'Barkal',
    'Belaichhari',
    'Juraichhari',
    'Kaptai',
    'Kaukhali',
    'Langadu',
    'Naniarchar',
    'Rajasthali',
    'Rangamati Sadar',
  ],
  Rangpur: [
    'Badarganj',
    'Gangachhara',
    'Kaunia',
    'Mithapukur',
    'Pirgachha',
    'Pirganj',
    'Rangpur Sadar',
    'Taraganj',
  ],
  Satkhira: [
    'Assasuni',
    'Debhata',
    'Kalaroa',
    'Kaliganj',
    'Satkhira Sadar',
    'Shyamnagar',
    'Tala',
  ],
  Shariatpur: [
    'Bhedarganj',
    'Damudya',
    'Gosairhat',
    'Naria',
    'Shariatpur Sadar',
    'Zajira',
  ],
  Sherpur: [
    'Jhenaigati',
    'Nakla',
    'Nalitabari',
    'Sherpur Sadar',
    'Sreebardi',
  ],
  Sirajganj: [
    'Belkuchi',
    'Chauhali',
    'Kamarkhanda',
    'Kazipur',
    'Raiganj',
    'Shahjadpur',
    'Sirajganj Sadar',
    'Tarash',
    'Ullapara',
  ],
  Sunamganj: [
    'Bishwamvarpur',
    'Chhatak',
    'Derai',
    'Dharampasha',
    'Dowarabazar',
    'Jagannathpur',
    'Jamalganj',
    'Madhyanagar',
    'Shantiganj',
    'Sullah',
    'Sunamganj Sadar',
    'Tahirpur',
  ],
  Sylhet: [
    'Balaganj',
    'Beanibazar',
    'Bishwanath',
    'Companiganj',
    'Dakshin Surma',
    'Fenchuganj',
    'Golapganj',
    'Gowainghat',
    'Jaintiapur',
    'Kanaighat',
    'Osmani Nagar',
    'Sylhet Sadar',
    'Zakiganj',
  ],
  Tangail: [
    'Basail',
    'Bhuapur',
    'Delduar',
    'Dhanbari',
    'Ghatail',
    'Gopalpur',
    'Kalihati',
    'Madhupur',
    'Mirzapur',
    'Nagarpur',
    'Sakhipur',
    'Tangail Sadar',
  ],
  Thakurgaon: [
    'Baliadangi',
    'Haripur',
    'Pirganj',
    'Ranisankail',
    'Thakurgaon Sadar',
  ],
};
