// Thana/delivery-area lists per district, keyed to match BD_DISTRICTS_BY_
// DIVISION's district names exactly. Sourced directly from Steadfast's own
// merchant-panel area picker (not the official government upazila list) —
// per explicit request, so the checkout dropdown only ever offers values
// Steadfast itself already recognizes as real delivery zones, deduplicated
// (the source list had literal duplicate entries, e.g. two "Kadamtali").
// Only districts present here get a real dropdown in AddressFields.tsx —
// every other district still falls back to free-text entry until its own
// list is supplied the same way (see that file's fallback logic).
export const BD_THANAS_BY_DISTRICT: Record<string, string[]> = {
  Dhaka: [
    'Adabor',
    'Airport',
    'Ati Bazar (Keraniganj)',
    'Azompur',
    'Badda',
    'Banani',
    'Bangshal',
    'Bashundhara R/A',
    'Battery Section',
    'Bhashantek',
    'Cantonment',
    'Chalkbazar',
    'Dakshin khan',
    'Darus Salam',
    'Demra',
    'Dhanmondi',
    'Gandaria',
    'Gulistan',
    'Gulshan',
    'Hatirjheel',
    'Hazaribag',
    'Jatrabari',
    'Kadamtali',
    'Kafrul',
    'Kalabagan',
    'Kamrangirchar',
    'Khilgaon',
    'Khilkhet',
    'Kotwali',
    'Lalbagh',
    'Mirpur',
    'Mohammadpur',
    'Motijheel',
    'Mugda',
    'New Market',
    'Pallabi',
    'Paltan',
    'Panthapath',
    'Purbachal',
    'Ramna',
    'Rampura',
    'Rupnagar',
    'Sabujbag',
    'Shah Ali',
    'Shah Ali Market',
    'Shahbag',
    'Shahjahanpur',
    'Sher-e-Bangla Nagar',
    'Shyampur',
    'Sutrapur',
    'Tejgaon',
    'Tejgaon Industrial Area',
    'Turag',
    'Uttara',
    'Uttarkhan',
    'Vasantek',
    'Vatara',
    'Wari',
    'Zone Not Clear',
  ],
};
