"use client";

import { useRef, useState } from "react";

export interface ParsedHtmlPost {
  title?: string;
  metaDescription?: string;
  excerpt?: string;
  content?: string;
}

// Real DOMParser-based extraction — same fields the reference mockup's own
// script pulls: <title>/first <h1> for title, meta[name=description] for
// meta description, first <p> for excerpt, and the article/main/body content
// (scripts/styles/nav/header/footer stripped, the duplicate h1 removed) for
// the post body. Not a raw HTML dump into one field.
function parseHtml(html: string): ParsedHtmlPost {
  const doc = new DOMParser().parseFromString(html, "text/html");
  const h1 = doc.querySelector("h1");
  const title = (doc.querySelector("title")?.textContent || h1?.textContent || "").trim() || undefined;
  const metaDescription = doc.querySelector('meta[name="description"]')?.getAttribute("content")?.trim() || undefined;
  const firstP = doc.querySelector("article p, main p, body p");
  const excerpt = firstP?.textContent?.trim().slice(0, 200) || undefined;

  const container = doc.querySelector("article") ?? doc.querySelector("main") ?? doc.body;
  container.querySelectorAll("script, style, link, nav, header, footer").forEach((n) => n.remove());
  if (h1 && container.contains(h1)) h1.remove();
  const content = container.innerHTML.trim() || undefined;

  return { title, metaDescription, excerpt, content };
}

export function BlogHtmlDropzone({ onParsed }: { onParsed: (fields: ParsedHtmlPost) => void }) {
  const inputRef = useRef<HTMLInputElement>(null);
  const [dragging, setDragging] = useState(false);
  const [message, setMessage] = useState<{ text: string; error?: boolean } | null>(null);

  function handleFile(file: File) {
    if (!/\.html?$/i.test(file.name)) {
      setMessage({ text: "That file is not an HTML file. Choose a .html or .htm file.", error: true });
      return;
    }
    const reader = new FileReader();
    reader.onload = () => {
      const parsed = parseHtml(String(reader.result ?? ""));
      onParsed(parsed);
      setMessage({ text: `Parsed "${file.name}" — title, excerpt, meta and content have been filled in. Review before saving.` });
    };
    reader.readAsText(file);
  }

  return (
    <div>
      <div
        onClick={() => inputRef.current?.click()}
        onDragOver={(e) => {
          e.preventDefault();
          setDragging(true);
        }}
        onDragLeave={() => setDragging(false)}
        onDrop={(e) => {
          e.preventDefault();
          setDragging(false);
          if (e.dataTransfer.files[0]) handleFile(e.dataTransfer.files[0]);
        }}
        className={`cursor-pointer rounded-[10px] border-[1.5px] border-dashed bg-[#fafcff] p-[22px_16px] text-center transition-colors ${
          dragging ? "border-brand-500 bg-[#f2f7ff]" : "border-[#c8d6ec] hover:border-brand-500"
        }`}
      >
        <div className="mx-auto mb-2.5 grid h-[42px] w-[42px] place-items-center rounded-[11px] bg-brand-50 text-brand-500">
          <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
            <polyline points="17 8 12 3 7 8" />
            <line x1="12" y1="3" x2="12" y2="15" />
          </svg>
        </div>
        <div className="text-[0.8rem] font-bold text-text">Drop an HTML file here</div>
        <div className="mt-1 text-[0.7rem] leading-relaxed text-muted">
          Paste a page generated by <b className="text-brand-500">Claude</b> or <b className="text-brand-500">ChatGPT</b> — it will be parsed into title, excerpt, meta and content.
        </div>
        <div className="mt-2 text-[0.66rem] text-muted">.html or .htm · max 2 MB</div>
        <input
          ref={inputRef}
          type="file"
          accept=".html,.htm"
          hidden
          onChange={(e) => {
            if (e.target.files?.[0]) handleFile(e.target.files[0]);
          }}
        />
      </div>
      {message && (
        <div
          className="mt-3 flex items-start gap-2 rounded-[8px] p-[9px_12px] text-[0.72rem] font-bold leading-relaxed"
          style={
            message.error
              ? { background: "#feeaec", border: "1px solid #f8ccd3", color: "#e8465e" }
              : { background: "#e6f8ef", border: "1px solid #c8eeda", color: "#16a06d" }
          }
        >
          {!message.error && (
            <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" strokeWidth={2.5} strokeLinecap="round" strokeLinejoin="round" className="mt-0.5 flex-none">
              <polyline points="20 6 9 17 4 12" />
            </svg>
          )}
          {message.text}
        </div>
      )}
    </div>
  );
}
