// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/[...path]" | "/[locale]/account" | "/[locale]/account/addresses" | "/[locale]/account/orders" | "/[locale]/account/reviews" | "/[locale]/account/wishlist" | "/[locale]/blog" | "/[locale]/blog/[slug]" | "/[locale]/blog/[slug]/preview/[token]" | "/[locale]/blog/author/[id]" | "/[locale]/blog/category/[slug]" | "/[locale]/blog/tag/[slug]" | "/[locale]/brands/[slug]" | "/[locale]/categories/[slug]" | "/[locale]/checkout" | "/[locale]/collections/[slug]" | "/[locale]/faq" | "/[locale]/login" | "/[locale]/orders/[orderNumber]/invoice" | "/[locale]/pages/[slug]" | "/[locale]/products" | "/[locale]/products/[slug]" | "/[locale]/products/[slug]/preview/[token]" | "/[locale]/register" | "/[locale]/search" | "/[locale]/tags/[slug]" | "/[locale]/track"
type AppRouteHandlerRoutes = "/api/auth/login" | "/api/auth/logout" | "/api/auth/otp/verify" | "/api/auth/refresh" | "/api/auth/register" | "/api/auth/social-login" | "/api/backend/[...path]" | "/api/revalidate" | "/robots.txt" | "/sitemap.xml"
type PageRoutes = never
type LayoutRoutes = "/[locale]" | "/[locale]/account"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/[locale]": { "locale": string; }
  "/[locale]/[...path]": { "locale": string; "path": string[]; }
  "/[locale]/account": { "locale": string; }
  "/[locale]/account/addresses": { "locale": string; }
  "/[locale]/account/orders": { "locale": string; }
  "/[locale]/account/reviews": { "locale": string; }
  "/[locale]/account/wishlist": { "locale": string; }
  "/[locale]/blog": { "locale": string; }
  "/[locale]/blog/[slug]": { "locale": string; "slug": string; }
  "/[locale]/blog/[slug]/preview/[token]": { "locale": string; "slug": string; "token": string; }
  "/[locale]/blog/author/[id]": { "locale": string; "id": string; }
  "/[locale]/blog/category/[slug]": { "locale": string; "slug": string; }
  "/[locale]/blog/tag/[slug]": { "locale": string; "slug": string; }
  "/[locale]/brands/[slug]": { "locale": string; "slug": string; }
  "/[locale]/categories/[slug]": { "locale": string; "slug": string; }
  "/[locale]/checkout": { "locale": string; }
  "/[locale]/collections/[slug]": { "locale": string; "slug": string; }
  "/[locale]/faq": { "locale": string; }
  "/[locale]/login": { "locale": string; }
  "/[locale]/orders/[orderNumber]/invoice": { "locale": string; "orderNumber": string; }
  "/[locale]/pages/[slug]": { "locale": string; "slug": string; }
  "/[locale]/products": { "locale": string; }
  "/[locale]/products/[slug]": { "locale": string; "slug": string; }
  "/[locale]/products/[slug]/preview/[token]": { "locale": string; "slug": string; "token": string; }
  "/[locale]/register": { "locale": string; }
  "/[locale]/search": { "locale": string; }
  "/[locale]/tags/[slug]": { "locale": string; "slug": string; }
  "/[locale]/track": { "locale": string; }
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/otp/verify": {}
  "/api/auth/refresh": {}
  "/api/auth/register": {}
  "/api/auth/social-login": {}
  "/api/backend/[...path]": { "path": string[]; }
  "/api/revalidate": {}
  "/robots.txt": {}
  "/sitemap.xml": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/[locale]": never
  "/[locale]/account": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
