// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/[locale]/[...path]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/[...path]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/[...path]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/account/addresses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/addresses">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/account/addresses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/account/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/account/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/account/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/reviews">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/account/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/account/wishlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/wishlist">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/account/wishlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/blog/[slug]/preview/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/[slug]/preview/[token]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/blog/[slug]/preview/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/blog/author/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/author/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/blog/author/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/blog/category/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/category/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/blog/category/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/blog/tag/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/tag/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/blog/tag/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/brands/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/brands/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/brands/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/categories/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/categories/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/categories/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/collections/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/collections/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/collections/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/faq">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/login">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/orders/[orderNumber]/invoice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/orders/[orderNumber]/invoice">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/orders/[orderNumber]/invoice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/pages/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/pages/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/pages/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/products/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/products/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/products/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/products/[slug]/preview/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/products/[slug]/preview/[token]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/products/[slug]/preview/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/products">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/register">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/search">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/tags/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tags/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/tags/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/track/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/track">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/track/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/otp/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/otp/verify">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/otp/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/refresh">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/social-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/social-login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/social-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/backend/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/[...path]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/backend/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/revalidate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/revalidate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/revalidate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/robots.txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/robots.txt">> = Specific
  const handler = {} as typeof import("../../../src/app/robots.txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sitemap.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap.xml">> = Specific
  const handler = {} as typeof import("../../../src/app/sitemap.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/[locale]/account/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/account">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/account/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
